language: objective-c
osx_image: xcode9.1
xcode_project: RxFirebase
xcode_scheme: RxFirebase
xcode_sdk: iphonesimulator9.3
env:
  global:
    - FRAMEWORK_NAME=RxFirebase
#branches:
#  only:
#    - master
cache:
  directories:
    - vendor
      #    - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - bundle install --path vendor/bundle --jobs=4
    # - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
before_deploy:
  # - carthage build --no-skip-current
  # - carthage archive $FRAMEWORK_NAME
script:
  - xcodebuild test -scheme RxFirebase -destination 'platform=iOS Simulator,name=iPhone 6'

notifications:
  email: false
