# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
 - bundle install --path=vendor/bundle --jobs=4
 - bundle exec pod repo update --silent
 - bundle exec pod install --project-directory=Example

script:
 - pod lib lint
 - bundle exec fastlane scan
  #- set -o pipefail && xcodebuild test -workspace Example/RxFirebase.xcworkspace -scheme RxFirebase-Example -destination 'platform=iOS Simulator,name=iPhone 5s' ONLY_ACTIVE_ARCH=NO | xcpretty
